Make crash errors more user friendly
cloudant/couchdb-couch-replicator pull request #82
Opened 2016-10-10 05:04 UTC by nickva

* Expose errors previously hidden behind the "unknown" label. End users might
not always descipher the error, but having a specific error might lead to
getting help faster from other sources.

* Expose errors during replication start phase. Previously hidden by "shutdown"
reason. Startup is an area which is expected to generate errors more frequently,
as this is where source or target db is opend the first time. There was already
a mechanism to log and notify gen_event listeners with a friendly error message,
however scheduler only looked at the exit reason which was always shutdown.

During source failure for example `_scheduler/jobs` output would look like:

```
"history": [
            {
                "reason": "shutdown",
                "timestamp": "2016-10-10T03-59-47.696599Z",
                "type": "crashed"
            },
...
```

After this commit it should look like:

```
"history": [
            {
                "reason": "db_not_found: could not open http://adm:*****@localhost:15984/cdyno-0000001/",
                "timestamp": "2016-10-10T04-41-47.75992Z",
                "type": "crashed"
            },
...
```

2016-10-10 06:25 UTC, nickva commented
Travis CI checks are failing because of an upstream bug I introduced in a recent new feature. Sorry about that. Here is the related upstream pr to fix it:

https://github.com/apache/couchdb-couch/pull/204

Tests should pass again after upstream pr is merged and couch dep in apache repo is bumped.

2016-10-11 12:35 UTC, sagelywizard requested changes
Just the whitespace change, otherwise LGTM.

2016-10-11 12:35 UTC, sagelywizard commented on src/couch_replicator_scheduler_job.erl
> +
Mind removing that?

2016-10-11 14:30 UTC, nickva commented on src/couch_replicator_scheduler_job.erl
> +
Oops sorry. Will do.

2016-10-11 14:37 UTC, sagelywizard approved these changes

2016-10-11 15:28 UTC, rnewson commented
nice. +1

2016-10-11 15:31 UTC, merged