63012 scheduler better docs
cloudant/couchdb-couch-replicator pull request #83
Opened 2016-10-13 21:45 UTC by nickva

2016-10-13 22:20 UTC, nickva commented
Companion PR: https://github.com/cloudant/showroom/pull/90

2016-10-14 21:41 UTC, sagelywizard requested changes

2016-10-14 21:41 UTC, sagelywizard commented on src/couch_replicator_js_functions.hrl
>          }
Does this need to emit for all states? You're changing the view to only emit when it's failed or completed.

2016-10-14 21:41 UTC, sagelywizard commented on src/couch_replicator_scheduler.erl
> +    EtsOpts = [named_table, {read_concurrency, true}, {keypos, #job.id}],
Just curious: Is this change relevant to this commit?

2016-10-14 21:41 UTC, sagelywizard commented on src/couch_replicator.erl
> +        true ->
It's my stylistic preference that for small/simple case statements, you squish them down to four lines. E.g.

```
case Blah of
    foo -> 4;
    bar -> 99
end
```

2016-10-14 21:41 UTC, sagelywizard commented on src/couch_replicator.erl
> +        true ->
Could even do a one-liner as `case DocState of failed -> 1; _ -> 0 end,`

2016-10-14 21:41 UTC, sagelywizard commented on src/couch_replicator.erl
> +            unknown
Might want to log this as an error.

2016-10-14 21:41 UTC, sagelywizard commented on src/couch_replicator.erl
> +filter_replicator_doc_query(unknown, _States) ->
Spec?

2016-10-14 23:01 UTC, nickva commented on src/couch_replicator_js_functions.hrl
>          }
It specifically handles only failed and completed.

There will be other states for a while perhaps if we upgrade from dbnext master or older code like triggered or error but those will be update by the replicator to first "no state" then some may go to failed or completed.

2016-10-14 23:03 UTC, nickva commented on src/couch_replicator_scheduler.erl
> +    EtsOpts = [named_table, {read_concurrency, true}, {keypos, #job.id}],
The logic there is that for each _scheduler/docs request where we fold through the docs ets table, for each document we'd got to the scheduler and fetch a bit of summary about the state.  If scheduler is rescheduling we don't want the docs request to lock the table fetch a job, then release it.

2016-10-14 23:07 UTC, nickva commented on src/couch_replicator.erl
> +            unknown
Agreed. Good idea.

2016-10-14 23:07 UTC, nickva commented on src/couch_replicator.erl
> +        true ->
That makes see. It does looks silly stretched out that much for a single flag.

2016-10-14 23:14 UTC, nickva commented on src/couch_replicator.erl
> +            unknown
Looking at it some more maybe crashing is more appropriate.  This view should never index anything except completed and failed docs and we explicitly control that via the map function in the design doc. There might be some edge cases on upgrade if we change or downgrade code, but I don't know if it is worth it for that...

2016-10-14 23:16 UTC, nickva commented on src/couch_replicator.erl
> +filter_replicator_doc_query(unknown, _States) ->
Good idea.

2016-10-14 23:25 UTC, sagelywizard approved these changes

2016-10-14 23:43 UTC, merged

2016-10-17 16:58 UTC, rnewson commented on src/couch_replicator.erl
> +    Nodes = lists:usort([node() | nodes()]),
`:sort` should be sufficient, there won't be duplicates in that list.

2016-10-17 16:59 UTC, rnewson commented
+1

2016-10-17 17:53 UTC, nickva commented on src/couch_replicator.erl
> +    Nodes = lists:usort([node() | nodes()]),
Agreed. That's silly. Not sure why I used usort there.