Add start_time and state_time to _scheduler/jobs and _scheduler/docs
cloudant/couchdb-couch-replicator pull request #97
Opened 2016-11-01 21:05 UTC by nickva

Add _replication_start_time field to completed and failed replication document
updates.

`start_time` is defined as the time since the replication first was noticed by
the replicator. For a document-based replication it is when the document update
event reached couch replicator and the replication record was parsed from it.
For a _replicate replication it is the time when the POST request body was
parsed.

`state_time` is time of last state update.

2016-11-02 17:27 UTC, sagelywizard commented
Do we really need a `last_updated` field, given that the last entry in `history` has a timestamp?

2016-11-02 17:33 UTC, nickva commented
@sagelywizard oh you mean in the json output of jobs? I added it mainly for consistency. But you're right, we probably don't need it. I'll remove it

2016-11-02 20:21 UTC, sagelywizard requested changes

2016-11-02 20:21 UTC, sagelywizard commented on src/couch_replicator.erl
>                      {null, 0}
This is a badmatch.

2016-11-02 20:21 UTC, sagelywizard commented on src/couch_replicator.erl
> +                    StateT = couch_util:get_value(<<"_replication_state_time">>, Props, null),
Can we pull these `StartT` and `StateT` `get_value`s out of this case?

2016-11-02 20:29 UTC, nickva commented on src/couch_replicator.erl
> +                    StateT = couch_util:get_value(<<"_replication_state_time">>, Props, null),
good idea

2016-11-02 20:59 UTC, nickva commented on src/couch_replicator.erl
>                      {null, 0}
oops, sorry, you're right! fixed

2016-11-03 00:30 UTC, sagelywizard commented on src/couch_replicator.erl
> +    DocId = get_value(id, Props),
It's my preference that these are left as-is. It's yucky that we're using an import in the first place and I don't see much point in changing it.

2016-11-03 00:30 UTC, sagelywizard commented on src/couch_replicator.erl
> +        _Other ->
Why're you adding this extra case clause? IIUC the view can only emit a 3-element list.

2016-11-03 00:37 UTC, nickva commented on src/couch_replicator.erl
> +        _Other ->
The view used to emit something else and we already deployed on bigblue was wondering if  it is better to handle previous view results there instead of crashing?

2016-11-03 00:38 UTC, nickva commented on src/couch_replicator.erl
> +    DocId = get_value(id, Props),
I'll change it back

2016-11-03 16:48 UTC, sagelywizard commented on src/couch_replicator.erl
> +        _Other ->
We should probably either add a comment or an explicit "upgrade" clause.

2016-11-03 16:51 UTC, nickva commented on src/couch_replicator.erl
> +        _Other ->
Good idea. Will add a comment

2016-11-03 17:03 UTC, sagelywizard commented on src/couch_replicator.erl
> +    MapValue = get_value(value, Props),
Can we change this back to use the module name as well?

2016-11-03 17:05 UTC, nickva commented on src/couch_replicator.erl
> +    MapValue = get_value(value, Props),
Will do

2016-11-03 17:09 UTC, sagelywizard commented on src/couch_replicator_scheduler.erl
> +
Could you remove this bit of whitespace addition?

2016-11-03 17:11 UTC, nickva commented on src/couch_replicator_scheduler.erl
> +
Oops, sorry. Updated

2016-11-03 19:59 UTC, sagelywizard commented on src/couch_replicator_doc_processor.erl
> +            last_updated = os:timestamp()
Hrm. It's a little ugly that this is set in `worker_returned`, but it's set in `update_docs_row` for the other `worker_returned` clause. It'd be nice if they were set in the same spot, or at least at the same function call depth. Thoughts?

2016-11-03 20:06 UTC, nickva commented on src/couch_replicator_doc_processor.erl
> +            last_updated = os:timestamp()
Ah good point. Let's pull that up into worker_return then. All cases of update_docs_row update it so it can be done in one place only

2016-11-03 20:35 UTC, sagelywizard approved these changes
🏇

2016-11-03 20:50 UTC, merged